# 廢土對賭機器人設定檔
# 1. 每個設定的選項後面都有說明，請詳閱
# 2. 若出現 "" ，請在兩個雙引號內填入適當的文字，並請勿刪除雙引號
# 3. 若出現 [] ，且您僅有一項參數要填，請填 ["你的參數"]
# 4. 若出現 [] ，且您有兩項參數要填，請填 ["你的參數 1", "你的參數 2"] 
# 5. 若出現 [] ，且您有三項參數要填，請填 ["你的參數 1", "你的參數 2", "你的參數 3"] ，若更多參數則以此類推

# 必填區域
[general]
key = "" # Bot 金鑰，可加入 Jimmy Bot 的伺服器並開啟客服單取得
username = "mcf-bet-bot" # Bot 的代號，不一定要填實際的 Minecraft ID 或是電子郵件，僅能填英文和數字
serverIP = "mcfallout.net" # 伺服器 IP，為了避免伺服器卡頓而造成 Bot 無法使用，故新增了此項設定
discordBotToken = "" # Discord Bot 的 token，可至 Discord 開法者頁面取得
discordApplicationID = "" # Discord Bot 的 application id，可至 Discord 開法者頁面取得
whitelist = ["Jimmy4Real"] # 白名單的 Minecraft 玩家的 ID